In [1]:
import pandas as pd

In [8]:
df = pd.DataFrame([[1,2], [3,4],[5,6]], columns= ['A','B'])

In [12]:
df.tail(1)

   A  B
2  5  6

In [16]:
df.columns.tolist()

['A', 'B']

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [20]:
df.describe()

         A    B
count  3.0  3.0
mean   3.0  4.0
std    2.0  2.0
min    1.0  2.0
25%    2.0  3.0
50%    3.0  4.0
75%    4.0  5.0
max    5.0  6.0

## Loading DataFrame from Files

In [22]:
cData= pd.read_csv('./DataSet/college_value_tableau_ready.csv')

In [25]:
cData.head()

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,admission_rate_percent,admission_rate_band,admission_rate_band_order,admission_rate_status,admission_rate_reported_100_flag,admission_rate_interpretation_note,sat_average_context,sat_average_status,sat_interpretation_note,admissions_profile_availability
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,...,57.95,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,938.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,"Birmingham, AL",33.505697,-86.799345,Public,1,...,88.18,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1258.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
2,100690,Amridge University,Montgomery,AL,36117-3553,"Montgomery, AL",32.362609,-86.174010,Private nonprofit,2,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,"Huntsville, AL",34.724557,-86.640449,Public,1,...,68.57,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,1319.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,...,97.55,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,976.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available